name: monai
channels:
  - pytorch
  - defaults
  - nvidia
  - conda-forge
dependencies:
  - numpy>=1.20
  - pytorch>=1.9
  - torchvision>=0.10
  - cudatoolkit=11.3
  - pip
  - pip:
      - -r requirements-dev.txt
